[project]
name = "hih-gcc-re"
version = "0.1.0"
description = "Hashish Investment Holding — GCC Real Estate Intelligence (Scout, Parser, Underwriter)"
requires-python = ">=3.10"
dependencies = [
  "fastapi",
  "uvicorn",
  "pydantic>=2",
  "pandas",
  "numpy",
  "httpx",
  "python-multipart",
]
